In [62]:
import numpy as np

### original stored memory

In [63]:
s = np.array([1,1,1,0])

In [64]:
W = np.outer(s,s)

### W_ij matrix

In [65]:
W

array([[1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 0]])

In [66]:
np.fill_diagonal(W, 0)

In [67]:
W

array([[0, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0]])

### imperfect memory

In [68]:
x = np.array([0,0,1,0])

In [69]:
y = x
y

array([0, 0, 1, 0])

### updating the first node

In [70]:
z0 = x[0] + y.dot(W[:, 0])
z0

np.int64(1)

In [71]:
def val(y):
    if y>0:
        return 1
    else:
        return 0

In [72]:
y[0] = val(z0)
y

array([1, 0, 1, 0])

### updating all the nodes (sync)

In [73]:
for i in range(4):
    y[i] = val(x[i] + y.dot(W[:,i]))

### final restored memory

In [74]:
y

array([1, 1, 1, 0])