In [39]:
import numpy as np

In [40]:
S = np.array([1,1,1,-1])
z = np.outer(S,S)

In [41]:
equivalent = [1,1,1,0]

In [42]:
z

array([[ 1,  1,  1, -1],
       [ 1,  1,  1, -1],
       [ 1,  1,  1, -1],
       [-1, -1, -1,  1]])

In [43]:
np.fill_diagonal(z, 0)

In [44]:
z

array([[ 0,  1,  1, -1],
       [ 1,  0,  1, -1],
       [ 1,  1,  0, -1],
       [-1, -1, -1,  0]])

In [45]:
x = np.array([0,0,1,0])

In [46]:
y = x
y

array([0, 0, 1, 0])

In [47]:
z0 = x[0] + y.dot(z[:, 0])
z0

1

In [48]:
def val(y):
    if y>0:
        return 1
    else:
        return 0

In [49]:
y[0] = val(z0)
y

array([1, 0, 1, 0])

In [51]:
for i in range(4):
    y[i] = val(x[i] + y.dot(z[:,i]))
y

array([1, 1, 1, 0])